### ISSUE TITLE
Stapelverarbeitung

### ISSUE THREAD

**Issue by aruttkamp** [astridx/pkg_agadvents#10]
Ich möchte die Kalendereinträge des vergangenen Jahres in das neue Jahr ( 2024 ) kopieren. 
Leider fehlt die Option zum ausführen. 
![image](https://github.com/user-attachments/assets/d0d34d93-f132-4edf-bb34-3ac70cff1b18)

Soll das so ? Wird das nicht unterstützt ? 
Oder mache ich doch was falsch ?

**Comment by astridx** [comment]
Das wird nicht unterstützt.

**Comment by aruttkamp** [comment]
Schade. Danke für die schnelle Antwort !
