### ISSUE TITLE
.htaccess zersört Modul

### ISSUE THREAD

**Issue by monkshoody** [astridx/pkg_agadvents#3]
Hey Astrid,

ich habe dein Modul auf meiner Seite eingebunden und es funktioniert super. Wenn ich allerdings die .htaccess zur Benutzerregstrierung  aktiviere, sieht das Modul so aus:
![Screenshot 2021-11-18 085611](https://user-images.githubusercontent.com/73463758/142374897-891c0a2d-08ac-456b-8dba-e00f578236be.png)

Der Inhalt meiner .htaccess ist:
AuthUserFile /var/www/html/.htpasswd
AuthName "Login"
AuthType Basic
order deny,allow
allow from all
require valid-user

Hast du eine Idee was da passiert?

**Comment by astridx** [comment]
Nutzt du Joomla 3 oder Joomla 4? Kann ich mir das online ansehen?

**Comment by monkshoody** [comment]
Ich nutze Joomla 4.0.4
Die Seite lautet: http://nosilentnight.ddnss.de/
Benutzer: Test
Passwort: test

**Comment by astridx** [comment]
Bist du sicher, dass der Fehler erst nach dem Hinzufügen der .htaccess auftrat?

Das Bild des Adventskalenders wird nicht korrekt in der Größe angepasst, weil im `<svg viewBox="0 0  " >`-Element die tatsächliche Größe nicht eingetragen ist. Das müsste richtig so aussehen: `<svg viewBox="0 0 905 1280">`.
In der Regel sind da Fehler im JavaScript der Verursacher. Bei dir sehe ich bei dem Rechtsklick-Script Fehler. Lösche das doch bitte einmal ganz und schau, ob es dann geht.

![1](https://user-images.githubusercontent.com/9974686/142431965-508d6e99-2deb-4c8d-ab15-768688fc7749.PNG)
![2](https://user-images.githubusercontent.com/9974686/142431973-9d21f356-566f-4818-9ec7-82411a9b32ab.PNG)

**Comment by monkshoody** [comment]
Ich habe die index.php angepasst aber leider ohne Erfolg. Die user.css habe ich auch schon überprüft.
Das Problem verschwindet bis nur wenn, ich die .htaccess deaktiviere.
Kann ich die Größe des Bildes nicht hardcoden?

**Comment by monkshoody** [comment]
Jap das wars. In der ./modules/mod_agadvent/tmpl/default.php wird der Wert <svg viewBox="0 0 905 1280"> auf <svg viewBox="0 0 " > verändert, wenn die .htacess aktiviert wird. Warum weiß ich nicht, aber der Wert kann hier einfach überschrieben werden und alles sieht gut aus.


Vielen Dank für die Hilfe!

p.S. Super Erweiterung.

**Comment by astridx** [comment]
> Kann ich die Größe des Bildes nicht hardcoden?

Wie du schon selbst gesehen hast, kannst du in einem Override die Werte fix setzten. Dann musst du allerdings selbst daran denken diese anzupassen, falls sich das Bild der Kategorie (dieses wird ja für den Adventskalender verwendet) einmal ändert.

**Comment by astridx** [comment]
> Jap das wars. In der ./modules/mod_agadvent/tmpl/default.php wird der Wert auf verändert, wenn die .htacess aktiviert wird. Warum weiß ich nicht, aber der Wert kann hier einfach überschrieben werden und alles sieht gut aus.
> 
> Vielen Dank für die Hilfe!
> 
> p.S. Super Erweiterung.

Danke für das Teilen deiner Lösung.

Ich würde gerne nachvollziehen, warum die Größe des Bildes mit aktivierte `.htaccess` nicht berechnet werden kann. Nutzt du das Bild aus den Beispieldateien oder ein eigenes mit einem anderen Datentyp als PNG?

**Comment by monkshoody** [comment]
Ich nutze das Bild aus den Beispieldateien.
Ich habe eine Vermutung aber die könnte auch weit hergeholt sein:
Um die .htaccess zu vewenden muss in der apache2.conf bzw. der httpd.conf der Wert `AllowOverride` angepasst werden. Dadurch dürfen htaccess-Dateien Vorgaben überschrieben und Ändern.
Im Joomla-Rootverzeichnis gibt eine `htaccess.txt` Datei (https://github.com/joomla/joomla-cms/blob/4.0-dev/htaccess.txt) in der folgendes Definiert wird ab Zeile 48:
## Disable inline JavaScript when directly opening SVG files or embedding them with the object-tag
<FilesMatch "\.svg$">
  <IfModule mod_headers.c>
    Header always set Content-Security-Policy "script-src 'none'"
  </IfModule>
</FilesMatch> 

Dadurch könnte der Wert verändert werden. Warum das aber nur die viewBox betrifft kann ich nicht sagen.

**Comment by astridx** [comment]
Danke für den Hinweis. Das hängt sicher mit der Content Security zusammen. Die `viewBox` ist ja ein Inline SVG.
Das muss ich mir genauer ansehen.
