### ISSUE TITLE
Anzahl Aufrufe pro "Türchen" ?

### ISSUE THREAD

**Issue by aruttkamp** [astridx/pkg_agadvents#9]
Hallo ! 
gibt es eine Möglichkeit zu sehen , wie oft ei Türchen aufgerufen wurde ? 
Vielleicht sogar "vor" dem eigentlichen Datum ? 

Andreas

**Comment by astridx** [comment]
Guten Morgen. Nein, die gibt es nicht.Viele Grüße Astrid
-------- Ursprüngliche Nachricht --------Von: Andreas Ruttkamp ***@***.***> Datum: 07.12.23  22:39  (GMT+01:00) An: astridx/pkg_agadvents ***@***.***> Cc: Subscribed ***@***.***> Betreff: [astridx/pkg_agadvents] Anzahl Aufrufe pro "Türchen" ? (Issue #9) 
Hallo !
gibt es eine Möglichkeit zu sehen , wie oft ei Türchen aufgerufen wurde ?
Vielleicht sogar "vor" dem eigentlichen Datum ?
Andreas

**Comment by aruttkamp** [comment]
Alles klar ! Vielen Dank !
